### PR TITLE
Resolve test issue with CTD call.  Change from http to https protocol.

### PR DESCRIPTION
**Pull request by cnbennett3**

### CODE REVIEW

**Comment by stevencox** [comment]
@YaphetKG & @cnbennett3 thanks for handling this. Please also verify that the fix for the missing chemical annotation file is preserved.

**Comment by YaphetKG** [comment]
@stevencox  the missing chemical annotation that I am aware of linked to CTD API (was there other changes?) , If none are present, I think CTD is good.

**Comment by stevencox** [comment]
Right - the fix would have been in the smartBag repo, right?

**Comment by YaphetKG** [comment]
Yes

**Pull request merged**
